name: jdlcommunity_getx
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_localization: ^0.1.14
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  get: 4.6.0
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  http: ^1.0.0
  intl: ^0.18.0
  shared_preferences: ^2.2.2
  skeletonizer: ^0.8.0
  sqflite: ^2.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  test: ^1.24.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/cover/
